#!/usr/bin/env python3
"""Cross-implications stage — the second-order reasoning the per-gate tracker can't do.

The gate tracker analyses each constraint IN ISOLATION ("chips stuck, power widening,
diffusion closing"). It never asks the question that decides the race: given a gate is
stuck, does a SUBSTITUTE route around it, or does the gated thing not even bind the
outcome that captures value? e.g.:
  - chips are stuck for TRAINING — but does distillation/efficiency route China around it
    so its inference + energy + open-weight edge wins the outcome that matters?
  - does 5nm matter for INFERENCE clusters, or only training clusters?
  - if models are 'good enough', is the value in economy-wide USE, not intelligence
    creation — so whoever deploys widest/cheapest wins, not whoever trains biggest?
  - do asymmetric adoption rules (US healthcare/liability caution vs China state push)
    hand China more of the deployment surplus even at equal capability?

This stage walks the composed graph's substitutes_for / gates edges + the gate trends +
the corpus, generates these cross-gate chains, and reasons each through (web-grounded,
evidence for/against, committed verdict + probability, effect on who-wins).

    python run_crossimplications.py     # reads bench/gate-tracker.json + composed-graph.json
"""
from __future__ import annotations
import glob, json, os, re, sys
from typing import Literal
from dotenv import load_dotenv
from pydantic import BaseModel, Field
from forecaster.llm import LLM

TRACKER = "bench/gate-tracker.json"
GRAPH = "bench/composed-graph.json"
OUT_JSON = "bench/cross-implications.json"
OUT_MD = "docs/cross-implications.md"


class CrossImplication(BaseModel):
    title: str = Field(description="The provocative thesis in one line, e.g. 'Distillation routes China around the training-compute gate — so inference + energy win the outcome that matters'.")
    question: str = Field(description="The cross-gate question it answers.")
    move_type: Literal["substitution", "scope_of_constraint", "value_locus_shift", "asymmetric_adoption", "compounding"] = Field(
        description="The type of second-order move: substitution (a workaround routes around the gate); scope_of_constraint (the gated input only binds part of the value chain, e.g. 5nm binds training not inference); value_locus_shift (value is in USE/economy not intelligence-creation, so 'good enough' + widest deployment wins); asymmetric_adoption (structural/regulatory factors mean the same capability yields different economic returns per actor); compounding (a feedback loop, e.g. AI accelerating AI R&D).")
    gates_connected: list[str] = Field(description="Which gates this chain links (ids or names).")
    reasoning_chain: str = Field(description="The chain: Gate A does X; but [substitute/route/relevance-limit] S; therefore the thing that actually binds the VALUE-capturing outcome is C — not A.")
    evidence_for: str = Field(description="Grounded support — cite corpus notes/analogies and web-checked facts.")
    evidence_against: str = Field(description="The steelman against the reframe (e.g. model collapse under synthetic data; distillation can't exceed the teacher; inference ALSO needs advanced nodes at scale).")
    verdict: str = Field(description="A committed lean — does the reframe hold, and under what condition.")
    probability: float = Field(description="0-1, rounded 0.05: probability the reframe holds over the window.")
    implication_for_who_wins: str = Field(description="If it holds, how it changes the race / value-capture picture (who benefits, which gate stops mattering).")
    confidence: Literal["low", "medium", "high"]
    grounding: Literal["corpus", "web_verified", "model_knowledge"]


class CrossImplicationReport(BaseModel):
    seed_questions: list[str] = Field(description="The 8-12 sharpest cross-gate questions generated by walking the substitute/gate edges and the trends.")
    implications: list[CrossImplication] = Field(description="6-10 reasoned cross-implication chains.")
    biggest_reframe: str = Field(description="The single most consequential cross-implication — the one that most changes the who-wins conclusion if true.")
    synthesis: str = Field(description="What the set of cross-implications does to the overall thesis: which hardening gates turn out NOT to bind the value outcome, and where the real contest therefore is.")


SYSTEM = """You do SECOND-ORDER, cross-gate reasoning for a multi-input AI x mercantilism race. You are given per-gate trends (each constraint analysed in isolation), the composed graph's interaction edges (especially substitutes_for and gates), and a corpus of notes/analogies.

The per-gate view is not enough to call the race, because a hardening gate is strategically irrelevant if a SUBSTITUTE routes around it, if the gated input doesn't bind the value-capturing outcome, or if the value has migrated to a layer the gate doesn't touch. Your job is to generate and reason through those cross-gate chains.

You have WebSearch — use it to check the load-bearing empirical claims (e.g. does distillation close the training gap? does inference need leading-edge nodes at scale? is there a 'good enough' capability ceiling for most enterprise use?). Ground in the corpus notes/analogies where they apply (grounding='corpus'); mark web-checked facts 'web_verified'.

Method:
1. Walk the substitutes_for and gates edges and the gate trends. Generate 8-12 SHARP cross-gate questions of the form 'given gate A is [stuck/widening], does [substitute/route/relevance-limit] mean the outcome that captures value isn't actually gated?'. Cover the five move types: substitution, scope_of_constraint (does 5nm bind training only, not inference?), value_locus_shift (is the value in economy-wide USE not intelligence-creation, so 'good enough' + widest cheapest deployment wins?), asymmetric_adoption (do US regulatory/liability frictions in e.g. healthcare hand China more deployment surplus at equal capability?), compounding.
2. Reason the best 6-10 through: the chain, evidence FOR (grounded), the steelman AGAINST, a committed verdict + probability, and what it does to who-wins.
3. Name the single biggest reframe and synthesize what the set does to the thesis — which hardening gates turn out NOT to bind the value outcome, and where the real contest therefore sits.

Be bold and non-obvious — the point is to surface the chains a per-gate reading misses — but every chain must survive its own steelman and rest on evidence, not vibes."""


def _tracker_summary(t: dict) -> str:
    L = ["GATE TRENDS (each analysed in isolation):"]
    for g in t.get("gates", []):
        dirs = "/".join(sorted({m["direction"] for m in g.get("metrics", [])}))
        L.append(f"[{g['gate_id']}] {g['gate_name']} — {dirs}; {g.get('hard_or_soft','')}")
        L.append(f"    forward: {g.get('forward_call','')[:220]}")
        if g.get("implications_if_holds"):
            L.append(f"    if-holds: {g['implications_if_holds'][:240]}")
    if t.get("synthesis"):
        L.append("\nCROSS-GATE READ (from the tracker):")
        L.append("  " + t["synthesis"].get("cross_gate_read", "")[:600])
    return "\n".join(L)


def _edges(g: dict) -> str:
    byid = {v["id"]: v["name"][:44] for v in g["merged_variables"]}
    L = ["INTERACTION EDGES (the routing structure):"]
    for e in g["edges"]:
        if e["kind"] in ("substitutes_for", "gates", "chokepoint_controlled_by"):
            L.append(f"  {e['source']}({byid.get(e['source'],'?')}) -{e['kind']}-> "
                     f"{e['target']}({byid.get(e['target'],'?')}): {e.get('note','')[:110]}")
    return "\n".join(L)


CROSS_KEYS = re.compile(
    r"(distillation|synthetic data|good enough|inference|training cluster|mature node|"
    r"substitut|route around|value.{0,12}(use|application|deployment|economy)|adoption|"
    r"self-suffic|commoditi|demand asymptote|compounding|accelerat\w+ AI|leverage window)", re.I)


def _corpus_notes(k: int = 26) -> str:
    seen, hits = set(), []
    for f in glob.glob("runs/*/notes*.json"):
        tid = os.path.basename(os.path.dirname(f)).split("-")[0]
        for n in json.load(open(f, encoding="utf-8")).get("notes", []):
            if n.get("type") not in ("theory", "hypothesis", "crux", "evidence_for", "evidence_against"):
                continue
            txt = f"{n.get('claim','')} {n.get('detail','')}"
            if CROSS_KEYS.search(txt):
                key = n.get("claim", "")[:60]
                if key in seen:
                    continue
                seen.add(key)
                hits.append(f"  [{tid} {n['type']}] {n.get('claim','')}: {(n.get('detail','') or '')[:170]}")
    return "RELEVANT CORPUS NOTES (prefer & cite; grounding='corpus'):\n" + "\n".join(hits[:k])


def _md(r: CrossImplicationReport) -> str:
    L = ["# Cross-implications — second-order chains across the gates\n",
         "*Where a per-gate reading stops, this begins: does a hardening gate actually bind the "
         "outcome that captures value, or does a substitute route around it / the value sit in a "
         "layer the gate doesn't touch? Web-grounded; corpus-cited.*\n",
         f"**Biggest reframe:** {r.biggest_reframe}\n",
         f"**Synthesis:** {r.synthesis}\n",
         "## Seed questions"]
    for q in r.seed_questions:
        L.append(f"- {q}")
    L.append("\n## Cross-implication chains")
    for c in sorted(r.implications, key=lambda x: -x.probability):
        L.append(f"\n### {c.title}")
        L.append(f"_[{c.move_type}] · links {', '.join(c.gates_connected)} · P={c.probability:g} · conf {c.confidence} · {c.grounding}_\n")
        L.append(f"**Question:** {c.question}")
        L.append(f"**Chain:** {c.reasoning_chain}")
        L.append(f"**For:** {c.evidence_for}")
        L.append(f"**Against (steelman):** {c.evidence_against}")
        L.append(f"**Verdict:** {c.verdict}")
        L.append(f"**If it holds → who wins:** {c.implication_for_who_wins}")
    return "\n".join(L)


def main() -> int:
    load_dotenv()
    for p in (TRACKER, GRAPH):
        if not os.path.exists(p):
            print(f"missing {p} — run the gate tracker / compose first."); return 1
    t = json.load(open(TRACKER, encoding="utf-8"))
    g = json.load(open(GRAPH, encoding="utf-8"))
    user = ("\n\n".join([_tracker_summary(t), _edges(g), _corpus_notes(),
                         f"WORLDVIEW: {g.get('worldview','')}"]) +
            "\n\nGenerate the cross-gate seed questions, reason the best 6-10 chains through "
            "(web-grounded, evidence for/against, verdict + probability, effect on who-wins), name "
            "the biggest reframe, and synthesise what the set does to the thesis.")
    llm = LLM()
    print("cross-implications reasoning (web-grounded, a few minutes)…\n")
    r = llm.parse(system=SYSTEM, user=user, schema=CrossImplicationReport,
                  tools=["WebSearch"], max_turns=24, call_timeout=1200, retries=1)
    json.dump(r.model_dump(), open(OUT_JSON, "w", encoding="utf-8"), indent=2)
    open(OUT_MD, "w", encoding="utf-8").write(_md(r))
    print(f"✓ {len(r.seed_questions)} seed questions, {len(r.implications)} chains reasoned")
    print(f"  biggest reframe: {r.biggest_reframe[:100]}")
    if llm.last_cost_usd:
        print(f"  cost: ${llm.last_cost_usd:.2f}")
    print(f"  wrote {OUT_MD} and {OUT_JSON}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
